# Generated by Django 5.2.10 on 2026-01-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='项目名称')),
                ('description', models.TextField(verbose_name='项目描述')),
                ('image', models.ImageField(upload_to='project_images/', verbose_name='项目封面')),
                ('github_link', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '个人项目',
                'verbose_name_plural': '个人项目管理',
            },
        ),
    ]
