# Generated by Django 5.2.10 on 2026-01-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_created_at_alter_project_github_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/', verbose_name='项目附件'),
        ),
    ]
