# Generated by Django 5.2.10 on 2026-01-16 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='file',
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, verbose_name='GitHub仓库'),
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(help_text='例如: v1.0, v2.0 beta', max_length=50, verbose_name='版本号')),
                ('file', models.FileField(upload_to='porject_files/', verbose_name='项目附件')),
                ('release_note', models.TextField(blank=True, verbose_name='更新日志/版本说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目版本',
                'verbose_name_plural': '版本管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
