# Generated by Django 5.2.10 on 2026-01-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_options_remove_project_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': '项目', 'verbose_name_plural': '项目管理'},
        ),
    ]
