# Generated by Django 5.2.10 on 2026-01-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_project_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签')),
                ('slug', models.SlugField(unique=True, verbose_name='标签别名 (URL用) ')),
                ('color', models.CharField(default='primary', help_text='可选：primary, secondary, success, danger, warning, info, dark', max_length=20, verbose_name='Bootstrap颜色')),
            ],
            options={
                'verbose_name': '项目标签',
                'verbose_name_plural': '标签管理',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='main.tag', verbose_name='项目标签'),
        ),
    ]
